# Execute this app
execute: App/Register, App/Asset, App/Welcome
# Language
lang: ID
# App Services
services:
    symfony.context:
        class: Symfony\Component\Routing\RequestContext
    symfony.matcher:
        class: Symfony\Component\Routing\Matcher\UrlMatcher
        arguments: ['%routes%','@symfony.context']
    symfony.resolver:
        class: Symfony\Component\HttpKernel\Controller\ControllerResolver
    symfony.finder:
        class: Symfony\Component\Finder\Finder
    symfony.filesystem:
        class: Symfony\Component\Filesystem\Filesystem
    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: ['%template_dir%']
    twig.environment:
        class: Twig_Environment
        arguments: ['@twig.loader']
