routes:
    register:
        path: /register
        defaults: { _controller: 'App\Register\Register::indexPage' }
    login:
        path: /register/login
        defaults: { _controller: 'App\Register\Register::loginPage'}
    forgot:
        path: /register/forgot
        defaults: { _controller: 'App\Register\Register::forgotPage'}
    action:
        path: /register/action/a
        defaults:
            _controller: 'App\Register\Register::actionPage'
services:
    app.register-process:
        class: App\Register\Process
